/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_LEFT.h>
#include <PWM_RIGHT.h>
#include <CLOCK_LEFT.h>
#include <CLOCK_RIGHT.h>
#include <controlRegStep.h>
#include <usbUART115200bps.h>
#include <usbUART115200bps_SPI_UART.h>
#include <usbUART115200bps_PINS.h>
#include <usbUART115200bps_SPI_UART_PVT.h>
#include <usbUART115200bps_PVT.h>
#include <pinLeftStep.h>
#include <pinLeftStep_aliases.h>
#include <pinRightStep.h>
#include <pinRightStep_aliases.h>
#include <pinLeftDir.h>
#include <pinLeftDir_aliases.h>
#include <pinRightDir.h>
#include <pinRightDir_aliases.h>
#include <pinLeftSleep.h>
#include <pinLeftSleep_aliases.h>
#include <pinRightSleep.h>
#include <pinRightSleep_aliases.h>
#include <ISR_UpdateSpeed.h>
#include <TIMER_ThreadTimer.h>
#include <CLOCK_ThreadClock.h>
#include <Bootloadable_1.h>
#include <usbUART115200bps_rx.h>
#include <usbUART115200bps_rx_aliases.h>
#include <usbUART115200bps_SCBCLK.h>
#include <usbUART115200bps_tx.h>
#include <usbUART115200bps_tx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

